default:
  image: reg.agarg.me/build/golang:latest-1.18.2-bullseye
  tags:
    - agarg-public-projects

stages:
  - test
  - build
  - release

.global-vars:
  variables:
    GOOS: linux
    GOARCH: amd64
    SCHISM_BIN: schism-lambda-${CI_COMMIT_REF_NAME}

fmt-vet-test:
  stage: test
  extends:
    - .global-vars
  before_script:
    - go get
    - go mod vendor
  script:
    - fmt_output=$(find -name vendor -prune -o -type f -name '*.go' -print0 | xargs -0 gofmt -l)
    - echo "${fmt_output}"
    - test -z "${fmt_output}"
    - go vet ./...
    - go test -cover -coverprofile cover.out ./...
    - go tool cover -func cover.out | awk '/total:/ {print $1" "$2" "$3}; /.go/{print $0}'
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hour

compile:
  stage: build
  extends:
    - .global-vars
  script:
    - go build -mod=vendor -ldflags "-extldflags '-static'" -o "${CI_PROJECT_DIR}/${SCHISM_BIN}" ./cmd...
    - zip "${SCHISM_BIN}".zip "${SCHISM_BIN}"
  artifacts:
    name: "compile_to_publish-$CI_COMMIT_REF_SLUG"
    expose_as: compile_to_publish
    paths:
      - ${SCHISM_BIN}.zip
      - .ci/publish
    expire_in: 1 hour
  dependencies:
    - fmt-vet-test

release:
  stage: release
  extends:
    - .global-vars
  variables:
    GIT_STRATEGY: none
  script:
    - sh .ci/publish
  dependencies:
    - compile
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      when: always
    - when: never
