default:
  image: img.doom.fm/build/golang:latest-1.14.2-buster
  tags:
    - shared-exec-docker

stages:
  - test
  - build
  - deploy

.global-vars:
  variables:
    GOOS: linux
    GOARCH: amd64
    SCHISM_BIN: schism-lambda-${CI_COMMIT_REF_NAME}

.go-cache:
  cache:
    key:
      files:
        - go.sum
      prefix: "${CI_COMMIT_REF_SLUG}"
    paths:
      - vendor/

fmt-vet-test:
  stage: test
  extends:
    - .global-vars
    - .go-cache
  before_script:
    - go mod vendor
  script:
    - go fmt ./...
    - go vet ./...
    - go test -cover -test.v ./...

compile:
  stage: build
  extends:
    - .global-vars
    - .go-cache
  script:
    - go build -ldflags "-extldflags '-static'" -o "${CI_PROJECT_DIR}/${SCHISM_BIN}" ./cmd...
    - zip "${SCHISM_BIN}".zip "${SCHISM_BIN}"
  artifacts:
    paths:
      - ${SCHISM_BIN}.zip
      - .ci/publish
    expire_in: 1 hour
  cache:
    policy: pull
  dependencies:
    - fmt-vet-test

release:
  stage: deploy
  extends:
    - .global-vars
  variables:
    GIT_STRATEGY: none
  script:
    - sh .ci/publish
  dependencies:
    - compile
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
      when: always
    - when: never
